
# thermostat-web-gateway-builder
FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

#COPY ./.s2i/environment "/usr/local/s2i"
ENV ARTIFACT_DIR=distribution ARTIFACT_COPY_ARGS="-r target/image/*"
